name       : open-vm-tools
version    : 10.3.5
release    : 127
source     :
    - https://github.com/vmware/open-vm-tools/archive/stable-10.3.5.tar.gz : c0ecd281d6113ca700b1ab0a10559db72e80d8fc03264d53ebfdc400578ab1b6
license    : LGPL-2.1
component  : system.utils
summary    :
    - open-vm-tools is a set of services and modules that enable several features in VMware products
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    open-vm-tools is a set of services and modules that enable several features in VMware products
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libmspack)
    - pkgconfig(libprocps)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xmlsec1)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - linux-lts
    - linux-lts-headers
    - libdnet-devel
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
optimize   : no-bind-now
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-set-Werror-it-s-evil.patch
    pushd open-vm-tools
    sed -i -e 's|.*common-agent/etc/config/Makefile.*||' configure.ac
    mkdir -p common-agent/etc/config
    %reconfigure --with-kernel-release="%kernel_version_lts%" \
                 --with-gtk3 \
                 --with-gtkmm3
    popd
build      : |
    %make -C open-vm-tools
install    : |
    %make_install -C open-vm-tools -j1
    install -Dm00644 $pkgfiles/vmtoolsd.service $installdir/%libdir%/systemd/system/vmtoolsd.service

    # Let LDM know about our aliases
    install -Dm00644 $pkgfiles/open-vm-tools.modaliases $installdir/usr/share/linux-driver-management/modaliases/open-vm-tools.modaliases

    install -d $installdir/usr/share/defaults/etc
    mv $installdir/etc/pam.d $installdir/usr/share/defaults/etc/pam.d
