name       : open-vm-tools
version    : 11.1.0
release    : 182
source     :
    - https://github.com/vmware/open-vm-tools/releases/download/stable-11.1.0/open-vm-tools-11.1.0-16036546.tar.gz : cb029af04357f19a899995f9e1ecfe55222b76158ab6d64fe8b56df0ccf87308
license    : LGPL-2.1-or-later
component  : system.utils
summary    :
    - open-vm-tools is a set of services and modules that enable several features in VMware products
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    open-vm-tools is a set of services and modules that enable several features in VMware products
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libmspack)
    - pkgconfig(libprocps)
    - pkgconfig(sm)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xmlsec1)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - linux-current-headers
    - libdnet-devel
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
optimize   : no-bind-now
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-set-Werror-it-s-evil.patch
    sed -i -e 's|.*common-agent/etc/config/Makefile.*||' configure.ac
    mkdir -p common-agent/etc/config
    %reconfigure --with-kernel-release="%kernel_version_current%" \
                 --with-gtk3 \
                 --with-gtkmm3
build      : |
    %make
install    : |
    %make_install -j1
    install -Dm00644 $pkgfiles/vmtoolsd.service $installdir/%libdir%/systemd/system/vmtoolsd.service

    # Let LDM know about our aliases
    install -Dm00644 $pkgfiles/open-vm-tools.modaliases $installdir/usr/share/linux-driver-management/modaliases/open-vm-tools.modaliases

    install -d $installdir/usr/share/defaults/etc
    mv $installdir/etc/pam.d $installdir/usr/share/defaults/etc/pam.d
