name       : open-vm-tools
version    : 10.1.5
release    : 52
source     :
    - https://github.com/vmware/open-vm-tools/archive/stable-10.1.5.tar.gz : aba7bf570b8951b61784941460659c204359d98fcbfb164df3c30d468a19fb1c
license    : LGPL-2.1
component  : system.utils
summary    : open-vm-tools is a set of services and modules that enable several features in VMware products
description: |
    open-vm-tools is a set of services and modules that enable several features in VMware products
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libmspack)
    - pkgconfig(sm)
    - pkgconfig(xerces-c)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - linux-lts
    - linux-lts-headers
    - libdnet-devel
    - xml-security-c-devel
optimize   : no-bind-now
setup      : |
    cd open-vm-tools
    %patch -p1 < $pkgfiles/0001-Don-t-set-Werror-it-s-evil.patch
    sed -i -e 's|.*common-agent/etc/config/Makefile.*||' configure.ac
    mkdir -p common-agent/etc/config
    %reconfigure --with-kernel-release="%kernel_version_lts%" --with-gtk3 --with-gtkmm3
build      : |
    cd open-vm-tools
    %make
install    : |
    cd open-vm-tools
    %make_install
