name       : open-vm-tools
version    : 10.1.5
release    : 100
source     :
    - https://github.com/vmware/open-vm-tools/releases/download/stable-10.1.5/open-vm-tools-10.1.5-5055683.tar.gz : d62fab6c0aeab5dccc96228a5674c1026a732da488fa5f83a396943e2826c17a
license    : LGPL-2.1
component  : system.utils
summary    :
    - open-vm-tools is a set of services and modules that enable several features in VMware products
    - modaliases : These files are used by the Software Center for hardware detection.
description: |
    open-vm-tools is a set of services and modules that enable several features in VMware products
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libmspack)
    - pkgconfig(libprocps)
    - pkgconfig(sm)
    - pkgconfig(xerces-c)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - linux-lts
    - linux-lts-headers
    - libdnet-devel
    - xml-security-c-devel
patterns   :
    - modaliases : /usr/share/linux-driver-management/modaliases
optimize   : no-bind-now
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-set-Werror-it-s-evil.patch
    %patch -p2 < $pkgfiles/security/cve-2015-5191.patch
    sed -i -e 's|.*common-agent/etc/config/Makefile.*||' configure.ac
    mkdir -p common-agent/etc/config
    %reconfigure --with-kernel-release="%kernel_version_lts%" --with-gtk3 --with-gtkmm3
build      : |
    %make
install    : |
    %make_install

    # Let LDM know about our aliases
    install -D -m 00644 $pkgfiles/open-vm-tools.modaliases $installdir/usr/share/linux-driver-management/modaliases/open-vm-tools.modaliases
