name       : open-vm-tools
version    : 10.0.7
release    : 11
source     :
    - https://github.com/vmware/open-vm-tools/archive/stable-10.0.7.tar.gz : 87d76dc3affd39dccfae80c7210ac89e8f14cb493a651709780f67b1b5a92ec8
license    : LGPL-2.1
component  : system.utils
summary    : open-vm-tools is a set of services and modules that enable several features
    in VMware products
description: |
    open-vm-tools is a set of services and modules that enable several features in VMware products
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libmspack)
    - pkgconfig(x11)
    - pkgconfig(xerces-c)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - kernel-headers
    - kernel-modules
    - libdnet-devel
    - xml-security-c-devel
setup      : |
    cd open-vm-tools
    %patch -p0 < $pkgfiles/no-unused-const.patch
    %patch -p0 < $pkgfiles/vmw-bitmask-gcc6.patch
    %reconfigure --without-gtkmm --with-kernel-release=4.8.3
build      : |
    cd open-vm-tools
    %make
install    : |
    cd open-vm-tools
    %make_install
